spring.application.name=coffee-management-api
server.port=8181

# PostgreSQL Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:4040/coffeedb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:brewstack}
spring.datasource.password=${DB_PASSWORD:brewstack123}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
